# Generated by Django 6.1.1 on 2026-10-04 12:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(blank=True, help_text='A familiar name shown in the web interface.', max_length=160, verbose_name='Name')),
                ('hostname', models.CharField(help_text='Hostname most recently reported by sanex.', max_length=253, verbose_name='Hostname')),
                ('version', models.CharField(blank=True, help_text='Installed sanex package version.', max_length=64, verbose_name='Version')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allowed', 'Allowed'), ('blocked', 'Blocked')], default='pending', help_text='Registration and client-access state.', max_length=16, verbose_name='Status')),
                ('certificate_fingerprint', models.CharField(blank=True, help_text='SHA-256 fingerprint of the issued client certificate.', max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Fingerprint must contain 64 lowercase hexadecimal characters.', regex='^[0-9a-f]{64}$')], verbose_name='Client certificate fingerprint')),
                ('public_key_fingerprint', models.CharField(blank=True, help_text='SHA-256 fingerprint of the registration CSR public key.', max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Fingerprint must contain 64 lowercase hexadecimal characters.', regex='^[0-9a-f]{64}$')], verbose_name='Public key fingerprint')),
                ('client_certificate', models.TextField(blank=True, editable=False, help_text='Issued client certificate retained for registration recovery.', verbose_name='Client certificate')),
                ('last_ip', models.GenericIPAddressField(blank=True, help_text='Source address of the latest authenticated request.', null=True, verbose_name='Last IP address')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Time of the latest authenticated request.', null=True, verbose_name='Last seen')),
                ('log_tail', models.TextField(blank=True, editable=False, help_text='Latest diagnostic log received from sanex.', verbose_name='Technical log')),
                ('log_received', models.DateTimeField(blank=True, editable=False, help_text='Server time when the latest diagnostic log was received.', null=True, verbose_name='Technical log received')),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone used to evaluate weekly schedules.', max_length=64, verbose_name='Timezone')),
                ('sync_interval', models.PositiveIntegerField(default=300, help_text='Seconds between successful complete synchronization cycles.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(86400)], verbose_name='Synchronization interval')),
                ('discovery_interval', models.PositiveIntegerField(default=30, help_text='Seconds between discovery attempts while synchronization is required.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Discovery interval')),
                ('walk_interval', models.PositiveIntegerField(default=1, help_text='Maximum seconds between session, window and process scans.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Walk interval')),
                ('save_interval', models.PositiveIntegerField(default=5, help_text='Maximum seconds between persistent runtime-state saves.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Save interval')),
                ('min_prc_duration', models.PositiveIntegerField(default=5, help_text='Minimum process duration in seconds retained in statistics.', validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Minimum process duration')),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computers',
                'ordering': ('hostname', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='IdentifierSequence',
            fields=[
                ('kind', models.CharField(choices=[('range', 'Schedule range'), ('session_rule', 'Session rule'), ('app_rule', 'Application rule')], max_length=32, primary_key=True, serialize=False, verbose_name='Kind')),
                ('next_ident', models.PositiveBigIntegerField(default=0, verbose_name='Next identifier')),
            ],
            options={
                'verbose_name': 'Identifier sequence',
                'verbose_name_plural': 'Identifier sequences',
            },
        ),
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(help_text='Name of this configuration snapshot or independent set.', max_length=160, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Limits set',
                'verbose_name_plural': 'Limits sets',
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PrcExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('prc_name', models.CharField(help_text='Exact case-sensitive name from /proc/PID/comm, up to 15 characters.', max_length=15, unique=True, validators=[django.core.validators.MaxLengthValidator(15)], verbose_name='Process name')),
                ('apply', models.BooleanField(default=True, editable=False, help_text='Include this exact name in configurations sent to sanex.', verbose_name='Ignore process')),
            ],
            options={
                'verbose_name': 'Ignored process',
                'verbose_name_plural': 'Ignored processes',
                'ordering': ('prc_name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('uid', models.PositiveBigIntegerField(help_text='Local account UID used by logind and process accounting.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='UID')),
                ('login', models.CharField(help_text='Login most recently reported by sanex.', max_length=256, verbose_name='Login')),
                ('name', models.CharField(help_text='Display name most recently reported by sanex.', max_length=256, verbose_name='Display name')),
                ('present', models.BooleanField(default=True, help_text='Whether the account is present in the latest complete snapshot.', verbose_name='Present')),
                ('collect', models.BooleanField(default=False, help_text='Collect session and process events for this account.', verbose_name='Collect events')),
                ('apply', models.BooleanField(default=False, help_text='Apply the account schedule and quota restrictions.', verbose_name='Apply limits')),
                ('computer', models.ForeignKey(help_text='Computer on which this local account exists.', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.computer', verbose_name='Computer')),
                ('limits', models.ForeignKey(blank=True, help_text='Immutable limits snapshot currently assigned to this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='core.limits', verbose_name='Limits')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ('computer', 'uid'),
            },
        ),
        migrations.CreateModel(
            name='ComputerConfig',
            fields=[
                ('ident', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('payload', models.BinaryField(help_text='Complete ready-to-send sanex configuration.', verbose_name='JSON payload')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='core.computer', verbose_name='Computer')),
            ],
            options={
                'verbose_name': 'Computer configuration',
                'verbose_name_plural': 'Computer configurations',
                'ordering': ('-ident',),
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='applied_config',
            field=models.ForeignKey(blank=True, editable=False, help_text='Configuration most recently confirmed by sanex.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_for_computers', to='core.computerconfig', verbose_name='Applied configuration'),
        ),
        migrations.AddField(
            model_name='computer',
            name='current_config',
            field=models.ForeignKey(blank=True, editable=False, help_text='Configuration currently offered to this computer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_computers', to='core.computerconfig', verbose_name='Current configuration'),
        ),
        migrations.CreateModel(
            name='EventPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('sha256', models.CharField(help_text='SHA-256 of the exact received JSONL bytes.', max_length=64, validators=[django.core.validators.RegexValidator(message='Fingerprint must contain 64 lowercase hexadecimal characters.', regex='^[0-9a-f]{64}$')], verbose_name='SHA-256')),
                ('first_seq', models.PositiveBigIntegerField(help_text='Sequence number of the first event in this packet.', verbose_name='First sequence')),
                ('last_seq', models.PositiveBigIntegerField(help_text='Sequence number of the last event in this packet.', verbose_name='Last sequence')),
                ('event_count', models.PositiveIntegerField(help_text='Number of events stored from this packet.', verbose_name='Event count')),
                ('byte_size', models.PositiveIntegerField(help_text='Size of the exact received JSONL body in bytes.', verbose_name='Byte size')),
                ('account', models.ForeignKey(help_text='Local account whose events were received.', on_delete=django.db.models.deletion.CASCADE, related_name='event_packets', to='core.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Event packet',
                'verbose_name_plural': 'Event packets',
                'ordering': ('account', 'first_seq', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('seq', models.PositiveBigIntegerField(help_text='Monotonic event number within the local account.', verbose_name='Sequence')),
                ('type', models.CharField(help_text='Protocol event type.', max_length=32, verbose_name='Type')),
                ('timestamp', models.PositiveBigIntegerField(help_text='Unix timestamp reported by sanex in whole seconds.', verbose_name='Timestamp')),
                ('run_ident', models.PositiveBigIntegerField(blank=True, help_text='Sequence number of the related session or process start.', null=True, verbose_name='Run identifier')),
                ('sess_ident', models.TextField(blank=True, help_text='Local logind session identifier.', null=True, verbose_name='Session identifier')),
                ('duration', models.PositiveBigIntegerField(blank=True, help_text='Observed active duration in seconds.', null=True, verbose_name='Duration')),
                ('prc_name', models.TextField(blank=True, help_text='Observed user application process name.', null=True, verbose_name='Process name')),
                ('exe', models.TextField(blank=True, help_text='Resolved executable path without command-line arguments.', null=True, verbose_name='Executable')),
                ('rule_ident', models.PositiveBigIntegerField(blank=True, help_text='Application rule involved in an enforcement failure.', null=True, verbose_name='Rule identifier')),
                ('wnd_ident', models.PositiveBigIntegerField(blank=True, help_text='Local window identifier involved in an enforcement failure.', null=True, verbose_name='Window identifier')),
                ('reason', models.CharField(blank=True, help_text='Protocol reason for an enforcement failure.', max_length=64, null=True, verbose_name='Reason')),
                ('meta', models.JSONField(default=dict, help_text='Type-specific event metadata.', verbose_name='Metadata')),
                ('account', models.ForeignKey(help_text='Local account to which this event belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='core.account', verbose_name='Account')),
                ('packet', models.ForeignKey(help_text='Received packet containing this event.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.eventpacket', verbose_name='Event packet')),
            ],
            options={
                'verbose_name': 'Activity event',
                'verbose_name_plural': 'Activity events',
                'ordering': ('account', 'seq'),
            },
        ),
        migrations.CreateModel(
            name='GlobalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('version', models.CharField(help_text='Exact sanex package version to install.', max_length=64, verbose_name='Target version')),
                ('index_url', models.URLField(help_text='Python package index used to install the target version.', max_length=2048, verbose_name='Package index URL')),
                ('active', models.BooleanField(default=True, editable=False, verbose_name='Active')),
                ('cancelled', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Cancelled')),
            ],
            options={
                'verbose_name': 'Global sanex update',
                'verbose_name_plural': 'Global sanex updates',
                'ordering': ('-created', '-pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='one_active_global_update')],
            },
        ),
        migrations.CreateModel(
            name='ClientCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('type', models.CharField(help_text='Command type understood by sanex.', max_length=64, verbose_name='Type')),
                ('payload', models.JSONField(default=dict, help_text='Command parameters sent to sanex.', verbose_name='Payload')),
                ('status', models.CharField(blank=True, choices=[('done', 'Done'), ('failed', 'Failed')], max_length=16, null=True, verbose_name='Result status')),
                ('error', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Result error')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='Completed')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.computer', verbose_name='Computer')),
                ('global_update', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='core.globalupdate', verbose_name='Global update')),
            ],
            options={
                'verbose_name': 'Client command',
                'verbose_name_plural': 'Client commands',
                'ordering': ('computer', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='LimitsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(help_text='Parent-facing template name.', max_length=160, verbose_name='Name')),
                ('current_limits', models.OneToOneField(help_text='Current immutable configuration snapshot for this template.', on_delete=django.db.models.deletion.PROTECT, related_name='current_for_template', to='core.limits', verbose_name='Current limits snapshot')),
            ],
            options={
                'verbose_name': 'Limits template',
                'verbose_name_plural': 'Limits templates',
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(help_text='Name shown to the parent in the browser interface.', max_length=160, verbose_name='Name')),
                ('limits_tpl', models.ForeignKey(blank=True, help_text="Template available for explicit assignment to this person's accounts.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='core.limitstemplate', verbose_name='Limits template')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Optional person to whom this concrete local account belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='core.person', verbose_name='Person'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('person', models.ForeignKey(blank=True, help_text='Optional person represented by this browser user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SessionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('ident', models.PositiveBigIntegerField(help_text='Stable identifier preserved when the rule is copied.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Identifier')),
                ('name', models.CharField(help_text='Parent-facing rule name; it does not affect accounting identity.', max_length=160, verbose_name='Name')),
                ('apply', models.BooleanField(default=True, help_text='Apply session quotas and nested application rules.', verbose_name='Apply limits')),
                ('max_sessions', models.PositiveIntegerField(blank=True, help_text='Maximum sessions in one range occurrence; empty means unlimited.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum sessions')),
                ('max_duration', models.PositiveIntegerField(blank=True, help_text='Maximum duration of one session in seconds; empty means unlimited.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum duration')),
                ('break_duration', models.PositiveIntegerField(default=7200, help_text='Required break duration in seconds; zero disables the break.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Break duration')),
                ('limits', models.ForeignKey(help_text='Limits set containing this rule.', on_delete=django.db.models.deletion.CASCADE, related_name='session_rules', to='core.limits', verbose_name='Limits')),
            ],
            options={
                'verbose_name': 'Session rule',
                'verbose_name_plural': 'Session rules',
                'ordering': ('limits', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('ident', models.PositiveBigIntegerField(help_text='Stable identifier of this range and its accounting budget.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Identifier')),
                ('apply', models.BooleanField(default=True, help_text='Include this range in the allowed weekly schedule.', verbose_name='Include in schedule')),
                ('weekday', models.PositiveSmallIntegerField(help_text='Weekday from zero for Monday through six for Sunday.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Weekday')),
                ('since', models.PositiveSmallIntegerField(help_text='Range start in minutes since midnight.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1439)], verbose_name='Start minute')),
                ('till', models.PositiveSmallIntegerField(help_text='Exclusive range end in minutes since midnight.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='End minute')),
                ('limits', models.ForeignKey(help_text='Limits set containing this range and its budget.', on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='core.limits', verbose_name='Limits')),
                ('session_rule', models.ForeignKey(help_text='Session and application quotas used by this range.', on_delete=django.db.models.deletion.PROTECT, related_name='ranges', to='core.sessionrule', verbose_name='Session rule')),
            ],
            options={
                'verbose_name': 'Schedule range',
                'verbose_name_plural': 'Schedule ranges',
                'ordering': ('limits', 'weekday', 'since', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='AppRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('ident', models.PositiveBigIntegerField(help_text="Stable identifier of this application's accounting budget.", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Identifier')),
                ('name', models.CharField(help_text='Parent-facing application name; it is not a recognition condition.', max_length=160, verbose_name='Name')),
                ('apply', models.BooleanField(default=True, help_text='Apply this application rule.', verbose_name='Apply limits')),
                ('max_launches', models.PositiveIntegerField(blank=True, help_text='Maximum launches in one range occurrence; empty means unlimited.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum launches')),
                ('max_time', models.PositiveIntegerField(blank=True, help_text='Maximum total usage time in seconds; empty means unlimited.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum time')),
                ('prc_name', models.CharField(blank=True, help_text='Optional process-name recognition condition.', max_length=256, null=True, verbose_name='Process name')),
                ('prc_name_match', models.CharField(blank=True, choices=[('exact', 'Exact'), ('contains', 'Contains'), ('regex', 'Regular expression')], help_text='Matching method for prc_name.', max_length=16, null=True, verbose_name='Process name match')),
                ('exe', models.CharField(blank=True, help_text='Optional resolved executable-path recognition condition.', max_length=4096, null=True, verbose_name='Executable')),
                ('exe_match', models.CharField(blank=True, choices=[('exact', 'Exact'), ('contains', 'Contains'), ('regex', 'Regular expression')], help_text='Matching method for exe.', max_length=16, null=True, verbose_name='Executable match')),
                ('wnd_title', models.CharField(blank=True, help_text='Optional current window-title recognition condition.', max_length=512, null=True, verbose_name='Window title')),
                ('wnd_title_match', models.CharField(blank=True, choices=[('exact', 'Exact'), ('contains', 'Contains'), ('regex', 'Regular expression')], help_text='Matching method for wnd_title.', max_length=16, null=True, verbose_name='Window title match')),
                ('session_rule', models.ForeignKey(help_text='Session rule containing this application rule.', on_delete=django.db.models.deletion.CASCADE, related_name='app_rules', to='core.sessionrule', verbose_name='Session rule')),
            ],
            options={
                'verbose_name': 'Application rule',
                'verbose_name_plural': 'Application rules',
                'ordering': ('session_rule', 'name', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='eventpacket',
            constraint=models.UniqueConstraint(fields=('account', 'sha256'), name='core_eventpacket_account_sha_unique'),
        ),
        migrations.AddConstraint(
            model_name='eventpacket',
            constraint=models.CheckConstraint(condition=models.Q(('first_seq__lte', models.F('last_seq'))), name='core_eventpacket_sequence_range_valid'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['account', 'timestamp'], name='core_event_account_time_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['account', 'type', 'timestamp'], name='core_event_account_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.UniqueConstraint(fields=('account', 'seq'), name='core_activityevent_account_seq_unique'),
        ),
        migrations.AddConstraint(
            model_name='clientcommand',
            constraint=models.UniqueConstraint(condition=models.Q(('status__isnull', True)), fields=('global_update', 'computer'), name='one_pending_global_update_per_computer'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('computer', 'uid'), name='core_account_computer_uid_unique'),
        ),
        migrations.AddConstraint(
            model_name='sessionrule',
            constraint=models.UniqueConstraint(fields=('limits', 'ident'), name='core_session_rule_limits_ident_unique'),
        ),
        migrations.AddConstraint(
            model_name='range',
            constraint=models.UniqueConstraint(fields=('limits', 'ident'), name='core_range_limits_ident_unique'),
        ),
        migrations.AddConstraint(
            model_name='range',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='core_range_weekday_valid'),
        ),
        migrations.AddConstraint(
            model_name='range',
            constraint=models.CheckConstraint(condition=models.Q(('since__gte', 0), ('till__lte', 1440), ('since__lt', models.F('till'))), name='core_range_interval_valid'),
        ),
        migrations.AddConstraint(
            model_name='apprule',
            constraint=models.UniqueConstraint(fields=('session_rule', 'ident'), name='core_app_rule_session_ident_unique'),
        ),
    ]
